name: renovate
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
env:
  RENOVATE_STORAGE: /tmp/renovate-cache
jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:43.129.0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Restore Renovate cache
        uses: actions/cache@v5
        with:
          path: ${{ env.RENOVATE_STORAGE }}
          key: renovate-${{ github.repository }}-${{ hashFiles('config.js') }}
          restore-keys: |
            renovate-${{ github.repository }}-
      - name: Run Renovate
        run: renovate
        env:
          RENOVATE_CONFIG_FILE: ${{ github.workspace }}/config.js
          LOG_LEVEL: "debug"
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_CACHE_DIR: ${{ env.RENOVATE_STORAGE }}
          RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
