name: renovate
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
env:
  RENOVATE_STORAGE: /tmp/renovate-cache
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Restore Renovate cache
        uses: actions/cache@v5
        with:
          path: ${{ env.RENOVATE_STORAGE }}
          key: renovate-${{ github.repository }}-${{ hashFiles('config.js') }}
          restore-keys: |
            renovate-${{ github.repository }}-
      - name: Prepare cache directory
        run: |
          mkdir -p ${{ env.RENOVATE_STORAGE }}
          sudo chmod 777 -R ${{ env.RENOVATE_STORAGE }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@83ec54fee49ab67d9cd201084c1ff325b4b462e4 # v46.1.10
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
          RENOVATE_CACHE_DIR: ${{ env.RENOVATE_STORAGE }}
